import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stringify as stringifyYaml } from "yaml";
import type { Registry, Truth } from "./types.ts";

function patternTruths(registry: Registry): Truth[] {
  return registry.truths.filter((truth) =>
    truth.status === "live" &&
    (truth.executor.emit === "semgrep" || truth.executor.kind === "semgrep") &&
    ((truth.executor.forbidden_line_patterns?.length ?? 0) > 0 || (truth.executor.forbidden_signals?.length ?? 0) > 0),
  );
}

function coderabbitTruths(registry: Registry): Truth[] {
  return registry.truths.filter((truth) =>
    truth.status === "live" &&
    (truth.executor.kind === "coderabbit" || truth.executor.emit === "coderabbit") &&
    Boolean(truth.executor.coderabbit_instruction),
  );
}

export interface CompileResult {
  tenant: string;
  semgrep: string;
  coderabbit: string;
  manifest: string;
}

export function compileRegistry(registry: Registry): CompileResult {
  const semgrepRules = patternTruths(registry).map((truth) => {
    const regexes = [
      ...(truth.executor.forbidden_line_patterns ?? []),
      ...(truth.executor.forbidden_signals ?? []).map((signal) =>
        signal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
      ),
    ];
    return {
      id: `truth-compiler.${truth.id}`,
      message: `${truth.id}: ${truth.statement.trim()}`,
      languages: truth.executor.languages ?? ["javascript", "typescript"],
      severity: "ERROR",
      metadata: {
        truth_id: truth.id,
        executor: truth.executor.kind,
        source: "truth-compiler",
      },
      paths: {
        include: truth.applies_to.paths ?? [],
        exclude: truth.applies_to.excluded_paths ?? ["**/*.test.ts", "**/__tests__/**"],
      },
      "pattern-regex": regexes.length === 1 ? regexes[0] : `(${regexes.join("|")})`,
    };
  });

  const semgrep = stringifyYaml({ rules: semgrepRules });

  const instructions = coderabbitTruths(registry).map((truth) => ({
    path: truth.executor.coderabbit_path ?? (truth.applies_to.paths?.[0] ?? "**"),
    instructions: `${truth.id}: ${truth.executor.coderabbit_instruction}`,
  }));
  const coderabbit = stringifyYaml({
    reviews: {
      path_instructions: instructions,
    },
  });

  const manifestLines = [
    `# ${registry.tenant.name} emitters`,
    "",
    "Generated by Truth Compiler. Copy Semgrep rules into the repo Semgrep config;",
    "copy path instructions into the org or repo CodeRabbit config with inheritance.",
    "Do not use these files as a second AI reviewer.",
    "",
    `Live truths: ${registry.truths.filter((truth) => truth.status === "live").length}`,
    `Semgrep rules: ${semgrepRules.length}`,
    `CodeRabbit path instructions: ${instructions.length}`,
    `Visible gaps: ${registry.truths.filter((truth) => truth.status === "gap" || truth.status === "proposed").length}`,
    "",
  ];

  return {
    tenant: registry.tenant.id,
    semgrep,
    coderabbit,
    manifest: manifestLines.join("\n"),
  };
}

export function writeCompileResult(registry: Registry, outDir: string): CompileResult {
  const compiled = compileRegistry(registry);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "semgrep.yml"), compiled.semgrep, "utf8");
  writeFileSync(join(outDir, "coderabbit-path-instructions.yaml"), compiled.coderabbit, "utf8");
  writeFileSync(join(outDir, "MANIFEST.md"), compiled.manifest, "utf8");
  return compiled;
}
